# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read




jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install poetry
      run: |
        make poetry-download
        export PATH="$HOME/.poetry/env:$PATH"
    - name: Install dependencies
      run: |
        pip install ruff pytest
    - name: Lint with ruff
      run: |
        ruff check . --select F401 --select F403 --quiet
    - name: Run style checks
      run: |
        make check-style
    - name: Run fast tests
      run: |
        make fast-test
    - name: Run safety checks
      run: |
        make check-safety
    - name: Test with pytest
      run: |
        make fast-test
        poetry run pytest -c pyproject.toml -v -m "not slow" test_sum.py
        
  
